name: smathy
favicon: null
layout_spectrum: 0.40094323246739805
typography_spectrum: 0.2947738249786198
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6233173068612814
  lightness: 0.32745276018977165
  saturation: 0.06546791736036539
  rhythmicContrast: 0.688031813595444
purpose: []
